### ISSUE TITLE
error[E0603]: module `shape` is private

### ISSUE THREAD

**Issue by lizelive** [QuartzLibrary/schema_analysis#3]
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/schema_analysis-0.3.4/src/targets/json_typegen.rs:13:5

**Comment by QuartzLibrary** [comment]
Hi @lizelive!

This doesn't show up for me, so more context on the error would be needed to fix it. 
It might go away by itself once I find the time to transition to using the new version of json-typegen now that the author has exposed the needed modules on a new version on cargo.io. Right now it uses a fork.

As a side note, if it's something you can share I would be curious as to how you are using the crate in the wild!

**Comment by QuartzLibrary** [comment]
This should be fixed by #1.
